### ISSUE TITLE
Question about the PHONE dataset

### ISSUE THREAD

**Issue by AlbertoJaenal** [yaqding/relative-pose-E4f#2]
Dear Mr. Ding
Thanks for providing the code and the data of your work.

I have a question about the PHONE dataset, related to the scale of the data. I have tried to test relative pose estimators in the image pairs given, but when I inspected the scale of the data, I found that it was excessively small. I paste here a plot of the translation values for the first sequence:
![image](https://github.com/yaqding/relative-pose-E4f/assets/23337326/ea0dfb08-7e4a-4e30-bfcf-a1be88e20b07)
Should the data be scaled somehow to get the real GT?
Best

**Comment by yaqding** [comment]
Hi,

Thank you for the comments. Since the dataset was built based on a Monocular camera, the ground truth for the translation is only up to a scale factor. So it's possible to evaluate the translation direction error, i.e., acos(Test'*Tgt/(norm(Test)*norm(Tgt))).

Best
